name: 'Create Unity Project'
description: 'Create new empty Unity3D project'
author: 'nowsprinting'

inputs:
  project_path:
    required: false
    description: 'Unity project path for create (relative from /github/workspace)'
    default: 'UnityProject~'

outputs:
  created_project_path:
    description: 'Created Unity project path (relative from /github/workspace)'

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'gray-dark'